# Generated by Django 3.2.4 on 2021-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='druhytext',
            field=models.CharField(default='', max_length=40),
        ),
    ]
