# Generated by Django 3.2.4 on 2021-06-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_druhytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='druhytext',
        ),
    ]
